apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: geobee-maps-backend
  newName: mesquitadev/gitops-maps
  newTag: f2829c3d5aa4f16556dd041e2d2f85a8906e18ea
