apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: geobee-maps-backend
  newName: mesquitadev/gitops-maps
  newTag: c261348d7011928485b5a67b11128e77441cc6ec
